export namespace LEVA {
  export enum ORDER {
    "GENERAL",
    "CANVAS",
    "EFFECTS_COMPOSER",
    "HELPERS",
    "PHYSICS",
    "SIMULATION",
    "COMPONENTS",
    "GEOMETRY",
    "MATERIALS",
    "MATERIAL",
    "BASIC_MATERIAL",
    "LAMBERT_MATERIAL",
    "PHONG_MATERIAL",
    "STANDARD_MATERIAL",
    "PHYSICAL_MATERIAL",
    "MATCAP_MATERIAL",
    "NORMAL_MATERIAL",
    "TOON_MATERIAL",
    "REFLECTOR_MATERIAL",
    "LIGHTING",
  }

  export enum SCHEMA {
    "BASIC_MATERIAL" = "Basic Material",
    "CANVAS" = "Canvas",
    "COMPONENTS" = "Components",
    "EFFECTS_COMPOSER" = "Effects Composer",
    "GENERAL" = "General",
    "GEOMETRY" = "Geometry",
    "HELPERS" = "Helpers",
    "LAMBERT_MATERIAL" = "Lambert Material",
    "LIGHTING" = "Lighting",
    "MATCAP_MATERIAL" = "Matcap Material",
    "MATERIAL" = "Material",
    "MATERIALS" = "Materials",
    "NORMAL_MATERIAL" = "Normal Material",
    "PHONG_MATERIAL" = "Phong Material",
    "PHYSICAL_MATERIAL" = "Physical Material",
    "PHYSICS" = "Physics",
    "REFLECTOR_MATERIAL" = "Reflector Material (Drei)",
    "SIMULATION" = "Simulation",
    "STANDARD_MATERIAL" = "Standard Material",
    "TOON_MATERIAL" = "Toon Material",
  }
}
